# Generated by Django 5.1.5 on 2025-02-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='character_signature',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Character Signature'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Personal Description'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nike_name',
            field=models.CharField(blank=True, default='', max_length=23, verbose_name='Name'),
        ),
    ]
