# Generated by Django 5.1.5 on 2025-02-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('desc', models.TextField(blank=True, default='', max_length=200, verbose_name='description')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='publish date')),
            ],
            options={
                'verbose_name': 'blog category',
                'verbose_name_plural': 'blog category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='tag name')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='publish date')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=61, verbose_name='title')),
                ('desc', models.TextField(blank=True, default='', max_length=200, verbose_name='description')),
                ('content', models.TextField(verbose_name='content')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='publish date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'article',
            },
        ),
    ]
