# Generated by Django 5.1.5 on 2025-02-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Module Name')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'search'), (2, 'Latest Articles'), (3, 'Top Articles'), (4, 'Recent Comments'), (5, 'Article Archives'), (6, 'HTML')], default=1, verbose_name='Display type')),
                ('content', models.CharField(blank=True, default='', help_text='If the type is not HTML, it can be null', max_length=500, verbose_name='content')),
                ('sort', models.PositiveIntegerField(default=1, help_text='The larger the number, the higher the number', verbose_name='sort')),
                ('status', models.PositiveIntegerField(choices=[(1, 'hide'), (2, 'display')], default=2, verbose_name='status')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add date')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
                'ordering': ['-sort'],
            },
        ),
    ]
