# Generated by Django 5.1.5 on 2025-02-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sidebar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['-sort'], 'verbose_name': 'Sidebar', 'verbose_name_plural': 'Sidebar'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='if the article is popular'),
        ),
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='page view'),
        ),
    ]
