# Generated by Django 5.1.5 on 2025-02-28 12:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_sidebar_options_post_is_hot_post_pv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'search'), (2, 'create a new post'), (3, 'Latest Articles'), (4, 'Hot Articles'), (5, 'Article Archives')], default=1, verbose_name='Display type'),
        ),
    ]
